name: app_template
description: NativeShell application template
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-214.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  path: ^1.7.0

  cupertino_icons: ^1.0.0
  nativeshell:
    version: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900